/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:bd25768c411f65901f5222d77f36c702:53c2cdc8fe718e1052ca2dcaffda6dfa:4411b07107cbdc652763aaf0b61f4918$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class unsaved
	{
		public const string BIOAgentConceptArt = "BIOAgentConceptArt";
		public const string BIOAgentConceptArt2 = "BIOAgentConceptArt2";
		public const string BIOAgentConceptArt3 = "BIOAgentConceptArt3";
	}
}